CREATE ROLE BaseUser;

GRANT SELECT, INSERT, UPDATE ON REPORT TO BaseUser;
GRANT SELECT ON USERS TO BaseUser;
GRANT SELECT, UPDATE ON STATUSHISTORY TO BaseUser;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMMENT TO BaseUser;

DROP ROLE BaseUser;

CREATE ROLE Manager;

GRANT SELECT, INSERT, UPDATE ON REPORT TO Manager;
GRANT SELECT ON USERS TO Manager;
GRANT SELECT, UPDATE ON STATUSHISTORY TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMMENT TO Manager;

DROP ROLE Manager;

CREATE ROLE UserAdmin;

GRANT SELECT, INSERT, UPDATE, DELETE ON REPORT TO UserAdmin;
GRANT SELECT, UPDATE, DELETE ON USERS TO UserAdmin;
GRANT SELECT, UPDATE ON STATUSHISTORY TO UserAdmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMMENT TO UserAdmin;

DROP ROLE UserAdmin;