CREATE ROLE BaseUser;

GRANT SELECT, INSERT, UPDATE ON REPORT TO BaseUser;
GRANT SELECT ON USERS TO BaseUser;
GRANT SELECT, UPDATE ON STATUSHISTORY TO BaseUser;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMMENT TO BaseUser;

DROP ROLE BaseUser;

CREATE ROLE UserAdmin;

GRANT SELECT, INSERT, UPDATE, DELETE ON REPORT TO UserAdmin;
GRANT SELECT, UPDATE, DELETE ON USERS TO UserAdmin;
GRANT SELECT, UPDATE ON STATUSHISTORY TO UserAdmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMMENT TO UserAdmin;

DROP ROLE UserAdmin;

CREATE USER user_admin WITH LOGIN PASSWORD '1234';
GRANT UserAdmin TO user_admin;

CREATE USER base_user WITH LOGIN PASSWORD '12345';
GRANT BaseUser TO base_user;